# Generated by Django 6.0.1 on 2026-01-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_autor_biografia_libro_anio_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
