# Generated by Django 6.0.1 on 2026-07-17 18:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_autor_imagen_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellidos', 'nombres']},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva']},
        ),
        migrations.AddField(
            model_name='autor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='libro',
            name='cantidad_total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='libro',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('devuelta', 'Devuelta'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='autor',
            name='imagen_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='libros.autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='libros.libro'),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['apellidos'], name='libros_auto_apellid_440d06_idx'),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=models.Index(fields=['nacionalidad'], name='libros_auto_naciona_593f45_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['titulo'], name='libros_libr_titulo_8b1204_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['genero'], name='libros_libr_genero_56ce56_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['actualizado_en'], name='libros_libr_actuali_59858a_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario'], name='libros_rese_usuario_a91bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='libros_rese_estado_302173_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_reserva'], name='libros_rese_fecha_r_40b202_idx'),
        ),
        migrations.AddConstraint(
            model_name='autor',
            constraint=models.UniqueConstraint(fields=('nombres', 'apellidos'), name='autor_nombre_completo_unico'),
        ),
    ]
